name: com.example.simple_counter
description: A simple Flutter application that demonstrates the use of the Cubit pattern for state management by implementing a basic counter that increments by 2.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true